### PR TITLE
recognize: use lstm_choice_mode=2 for textequiv_level=glyph

### LINKED ISSUE #7: also fill PAGE's glyphs and its variants and confidences via GetIterator() in recognize.py
For OCR postcorrection, `TextLine.Word.Glyph.TextEquiv` can be more valueable than just `TextLine.TextEquiv`. It allows to build up a lattice (or rather, confusion network) of alternative character hypotheses to (re)build words and phrases from. The PAGE notion of character hypotheses is glyph variants, i.e. a sequence of `TextEquiv` with `index` and `conf` (confidence) attributes. This does not help in addressing segmentation ambiguity (especially on the word level, since PAGE enforces a hierarchy of `Word`). But most ambiguity on the character level can still be captured.

Example: 
```XML
<TextLine id="...">
  <Coords points="..."/>
  <Word id="...">
    <Coords points="..."/>
    <Glyph id="...">
      <Coords points="..."/>
      <TextEquiv>
        <Unicode>a</Unicode>
      </TextEquiv>
    </Glyph>
    <Glyph id="...">
      <Coords points="..."/>
      <TextEquiv index="0" conf="0.6">
        <Unicode>m</Unicode>
      </TextEquiv>
      <TextEquiv index="1" conf="0.3">
        <Unicode>rn</Unicode>
      </TextEquiv>
      <TextEquiv index="2" conf="0.1">
        <Unicode>in</Unicode>
      </TextEquiv>
    </Glyph>
  </Word>
  <Word id="...">
    ...
  </Word>
  <TextEquiv>
    <Unicode>am Ende</Unicode>
  </TextEquiv>
</TextLine>
```

So this part of the wrapper should also dive into the word and character/glyph substructure as a complementary level of annotation. Tesseract's API seems to be straightforward for this use case: ``baseapi.h`` contains `GetIterator()` giving a `ResultIterator`, which allows to recurse across `RIL_SYMBOL` as `PageIteratorLevel`. For each glyph then a `GetUTF8Text()` and `Confidence()` yield what we need.

### PR DESCRIPTION
**Pull request by bertsky**
Fixes #7.

This does appear to work and not cause any more segfaults with recent Tesseract. At last!

### CODE REVIEW

**Comment by bertsky** [comment]
> This does appear to work and not cause any more segfaults with recent Tesseract.

Sorry, I was wrong: it still crashes!

**Comment by bertsky** [comment]
> Sorry, I was wrong: it still crashes!

@stweil, here is a backtrace:
```
02:49:05.188 DEBUG processor.TesserocrRecognize - Decoding text in glyph 'region0008_line0000_word0002_glyph0000'

Thread 1 "python" received signal SIGSEGV, Segmentation fault.
0x00007ffff3c0f6b6 in tesseract::ChoiceIterator::ChoiceIterator (this=0x179b6290, result_it=...) at ../src/ccmain/ltrresultiterator.cpp:389
389	    if (strcmp(word_res_->CTC_symbol_choices[0][0].first, " ")) {
(gdb) fr 0
(gdb) p word_res_->CTC_symbol_choices 
$2 = std::vector of length 3, capacity 4 = {std::vector of length 0, capacity 0, std::vector of length 2, capacity 2 = {{
      first = 0x12f9ad70 "S", second = 3.5559907}, {first = 0x12f9bdf8 "Y", second = 6.70712423}}, 
  std::vector of length 16, capacity 16 = {{first = 0x12f9bdf8 "Y", second = 1.94020641}, {first = 0x12f9ad70 "S", second = 4.29620028}, {
      first = 0x12f9ae28 "O", second = 19.4803467}, {first = 0x12f9a9d8 "E", second = 21.8223343}, {first = 0x12f9b838 "P", 
      second = 22.4020309}, {first = 0x12f9b610 "T", second = 21.7317104}, {first = 0x12f9aa90 "F", second = 22.6467323}, {
      first = 0x12f9b108 "G", second = 22.7008057}, {first = 0x12f9beb0 "Z", second = 23.6807079}, {first = 0x12f9a7b0 "N", 
      second = 23.8459435}, {first = 0x12f9b6c8 "I", second = 24.8425007}, {first = 0x12f9a868 "D", second = 24.6850224}, {
      first = 0x12f9b558 "M", second = 27.1605015}, {first = 0x12f9cf38 "]", second = 28.5629539}, {first = 0x12f9a6f8 "A", 
      second = 28.6672821}, {first = 0x12f9a640 "W", second = 29.0376415}}}
```

So it appears that the first glyph's choices are all empty. Does that suffice for you?

I think it will be difficult to share my whole workspace. This happened in the first glyph of the third word of the following line:
DEWARPED8-CLIP-LINEIMG_0005_region0008_region0008_line0000 bin

**Comment by bertsky** [comment]
I have a [fix](https://github.com/tesseract-ocr/tesseract/pull/2871).

So this can be merged independently I think. (We just have to make sure the PyPI release happens no earlier than the rebuild of the merged fix on alex-ppa and ocrd_all does not update ocrd_tesserocr before it updates tesseract.)

**Comment by stweil** [comment]
Thanks. The Tesseract fix is merged now, so I think this issue can be closed.

**Comment by kba** [comment]
Perfect, thanks for the quick fix. I'll release a new version once [the current nightly is in PPA](https://launchpad.net/~alex-p/+archive/ubuntu/tesseract-ocr)

**Pull request merged**
