### PR TITLE
fix deskewing

### PR DESCRIPTION
**Pull request by bertsky**
depends on (and abides by) the new image API from OCR-D/core#327

### CODE REVIEW

**Comment by bertsky** [comment]
Tests fail because core#311 and core#327 are not merged yet.

**Comment by bertsky** [comment]
I relaxed the requirements – `tesserocr==2.5.0` has not been published yet. What we really need is core, though.

**Comment by bertsky** [comment]
@kba you can release on PyPI now I think. As for merging... maybe in a (short-lived) extra branch here, too?

**Comment by kba** [comment]
Thanks!

> maybe in a (short-lived) extra branch here, too?

Yeah, I had an `edge` branch prepared but apparently forgot to push it... Will do now.

**Comment by kba** [comment]
Released as https://pypi.org/project/ocrd-tesserocr/0.5.0/, keeping changes in https://github.com/OCR-D/ocrd_tesserocr/tree/edge as long as ocrd 2.0.0 is pre-release. 

https://github.com/OCR-D/ocrd_tesserocr/pull/83 supersedes this.

**Pull request closed without merging**
