### PR TITLE
Don't raise exception for empty intersection (fix issue #139)

### PR DESCRIPTION
**Pull request by stweil**
Signed-off-by: Stefan Weil <sw@weilnetz.de>

### CODE REVIEW

**Comment by kba** [comment]
But if the child element is outside the parent element, that is an error that should be adressed. I agree that raising an exception shifts the responsibility for debugging to the user, that is not ideal. But this should be debugged nonetheless.

**Comment by stweil** [comment]
> But this should be debugged nonetheless.

Sure, that's why I added `LOG.error`. But you are right, this is not a fix but a workaround, so issue #139 should be kept open even with this commit.

**Comment by stweil** [comment]
> But if the child element is outside the parent element, that is an error that should be adressed.

Maybe both parent and child are empty, then the child is not outside, but the same error is triggered.

**Comment by bertsky** [comment]
Introducing this exception was a conscious decision for the current state of coordinate consistency in OCR-D.

We know that most processors currently write illegal coordinates sometimes, which ultimately fails at validation time with lots of hard to debug or trace or visualise error messages. But shifting the burden for correct coordinates from validation to implementation is a large effort, and we need core to support this as much as possible. That's where [this idea](https://github.com/OCR-D/core/issues/489#issuecomment-634731069) will step in.

But looking at the example in #139 I can now see that this will happen much more frequently than I thought in ocrd_tesserocr. So yes, we need to offer some workaround as well. I'll have to think about which is preferable: fixing this instance of #139 directly or downgrading to an error message...

**Comment by stweil** [comment]
Issue #139 is fixed now with a better solution, so closing this pull request.

**Pull request closed without merging**
